spring.application.name=EspritConnectBackend

spring.datasource.url=jdbc:mysql://localhost:3306/espritconnect?useUnicode=true&useJDBCCompliantTimezoneShift=true&createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
### JPA / HIBERNATE ###
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
#Server configuration
server.port=8086
server.servlet.context-path=/EspritConnect
logging.level.org.hibernate.SQL=ERROR
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.tn.esprit.espritconnectbackend=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
server.error.include-message=always
server.error.include-stacktrace=never

# Swagger/OpenAPI Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha

# Mail Configuration (Dummy config to satisfy JavaMailSender dependency)
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false



#AI API Configuration
nvidia.api.key=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