package tn.esprit.espritconnectbackend.entities.enums;

public enum NotificationType {
    CONNECTION_REQUEST,
    CONNECTION_ACCEPTED,
    POST_REACTION,
    POST_COMMENT,
    COMMENT_REPLY,
    EVENT_REMINDER,
    JOB_APPLICATION,
    MENTORING_REQUEST,
    MENTORING_ACCEPTED,
    MENTORING_REJECTED,
    MESSAGE_RECEIVED,
    GROUP_INVITE,
    GROUP_JOIN,
    GROUP_APPROVED,
    GROUP_REJECTED,
    NEWSLETTER,
    SYSTEM
}
